### ISSUE TITLE
Funding to Develop New Docker and for Future Maintenance and Support

### ISSUE THREAD

**Issue by dlandon** [dlandon/zoneminder.machine.learning#154]
We have set up a GoFundMe to fund the development of a new Docker that will be for Zoneminder and ES/ML with all the ES/ML modules pre-configured and for maintenance and support going forward.

[GoFundMe](https://www.gofundme.com/f/maintenance-of-zoneminder-docker-with-es-and-ml?utm_source=customer&utm_medium=copy_link&utm_campaign=p_cf+share-flow-1)

**Comment by rowandavies** [comment]
Is the plan to use nvidia-docker to avoid the need for semi-manual steps to install cuda inside the docker container?

**Comment by dlandon** [comment]
This is one of the things we will look at.

**Comment by McPaHa** [comment]
Will this support coral.ai usb accelerator?

**Comment by dlandon** [comment]
Support [here](https://forums.zoneminder.com/)

**Comment by doit2day** [comment]
Will zmninja ES+ML support discontinuance impact this project?

**Comment by dlandon** [comment]
I don't understand what you are talking about.

**Comment by doit2day** [comment]
Referring to the post at the following link: [https://forums.zoneminder.com/viewtopic.php?t=30996](https://forums.zoneminder.com/viewtopic.php?t=30996)

I was just wanting to make sure that this announcement wouldn't impact this project. I tried finding a way to not ask in a public forum, but I wasn't able to, sorry if this is the wrong place to discuss this.

**Comment by dlandon** [comment]
I will drop the support for this docker container.  Without ES & ML it is not very useful.
