### ISSUE TITLE
Export video?

### ISSUE THREAD

**Issue by ptruman** [dlandon/zoneminder.machine.learning#160]
This is more likely me, but currently I'm getting no video/images when exporting, and can't save video.

If I try to export I get:

Invalid log create: Array() | /usr/share/zoneminder/www/ajax/log.php

Can you point me in the right direction for the logs to check?
I'm on v1.35.16 (dlandon/zoneminder.master:latest)

**Comment by dlandon** [comment]
This is not being supported at this time. We will support this when the funding is raised in GoFundMe for the development and maintenance of a new Docker with ES/ML built in.
