### ISSUE TITLE
Original image removed ?

### ISSUE THREAD

**Issue by ugomeda** [dlandon/zoneminder.machine.learning#161]
Pulling the image dlandon/zoneminder returns a denied access, and the page on dockerhub (https://hub.docker.com/r/dlandon/zoneminder) returns 404.

Is this a mistake or shall we now subscribe to the gofundme to use the image ?

Thanks

**Comment by dlandon** [comment]
I'm getting ready and organizing for the new Docker container.  You do not have to donate to the GoFundMe.  It's your choice.  You'll never have to pay for the Docker.

**Comment by ugomeda** [comment]
Cool, thanks for the answer. I hope you can restore the images soon !
