### ISSUE TITLE
Reinstate existing docker hub image

### ISSUE THREAD

**Issue by michael-robbins** [dlandon/zoneminder.machine.learning#163]
Hey just checking if the disappearance of https://hub.docker.com/r/dlandon/zoneminder is expected?

My alerting started going off about 24 hours ago. Is there a new repo we should be using?

I can't really see anything similar here: https://hub.docker.com/u/dlandon

**Comment by michael-robbins** [comment]
Looking through the closed issues I can see other people with this and you're preparing for a new release.

Can we instead just reinstate and deprecate the image for now leaving it there so existing users don't error.

I see you are building the images in a new namespace `zoneminder.machine.learning` so there doesn't seem to be any reason to break everyone who is pulling `dlandon/zoneminder`?

**Comment by dlandon** [comment]
There is a docker container that will work the same but does not have machine learning - zoneminder.unraid.  It was made for Unraid, but will work on other systems.

Yes, I will be replacing this Docker with a new machine learning Docker.

**Comment by michael-robbins** [comment]
I guess my comment was more around 'lets not deliberately break things for existing users' than 'migrate to another similar image'.

This approach would have resulted in less noise for you (github issue spam) and the users of this image (less frustration as all their docker processes suddenly error with 404 messages).

But sure, up to you the maintainer of course :)
