### ISSUE TITLE
zmu utility fail with MySQL database query error

### ISSUE THREAD

**Issue by tazmad** [dlandon/zoneminder.machine.learning#164]
I'm running v1.34.22 (docker tag of dlandon/zoneminder:latest), while trying to run the zmu utility to try and generate a snapshot via command line I am getting the error:

`root@zoneminder:/# zmu --list --username admin --password 'secret_password'
01/30/21 22:32:30.741176 zmu[7454].ERR-zmu.cpp/726 [Can't run query: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '!= 'None' ORDER BY Id ASC' at line 1]

root@zoneminder:/# `

I have googled this and found the following "fix" https://github.com/ZoneMinder/zoneminder/issues/2885 however I am unable to find the required zmu.cpp file to edit within the container.  

Any suggestions would be much appreciated.

**Comment by dlandon** [comment]
This is not being supported at this time. We will support this when the funding is raised in GoFundMe for the development and maintenance of a new Docker with ES/ML built in.

**Comment by connortechnology** [comment]
This fix was merged in 1.34.13.  You are not running 1.34.22.
