### ISSUE TITLE
Zoneminder not processing Hooks (all manuals followed)

### ISSUE THREAD

**Issue by SuperMaximus1984** [dlandon/zoneminder.machine.learning#166]
Please help to figure out the issue with Zoneminder from your Docker container.
I attach my logs.
Even Server is configured correctly.
Docker was installed with all algorithms (Yolo3, TinyYolo3, Yolo4), config done successfully , IP address was pointed explicitly in 'secrets.ini',

I do not see any Motion object detection hooks in Events of ZM, the log is attached.
Should any message be registered instead "Motion:All"?
![image](https://user-images.githubusercontent.com/62514634/107433558-28ae9900-6b32-11eb-89ac-47f17a1166d7.png)

I'm wondering what's going wrong?
[zm-log (2).txt](https://github.com/dlandon/zoneminder.machine.learning/files/5954483/zm-log.2.txt)

Ready to participate in funding, please help.

**Comment by SuperMaximus1984** [comment]
Solved

**Comment by markcs** [comment]
@SuperMaximus1984  I realise this is a closed issue that you solved by yourself.  Can you share what you changed to get this working?  (I'm having the same issue)
