### ISSUE TITLE
Memory leak in latest version

### ISSUE THREAD

**Issue by TheOneOgre** [dlandon/zoneminder.machine.learning#167]
I recently have updated the docker container to the latest one. I know I am well behind on updating but for me, if something is working and is stable, I like to leave it, especially home security.

Anyways, the server is slowly leaking ram via the zmc processes and this was not happening with the last release. Everything works fine as it should, but over time (roughly 20 hours), the server will begin consuming more and more RAM, from 1gb to over 14gb (all that is free to it) and then start swapping. This drags everything else on the system down and prevents zoneminder from functioning properly. 

As this RAM usage climbs, a simple state change in the webUI to restart the monitors, releases all the used RAM, and the cycle starts over again. 

Nothing is shown in the debug logs, and not sure this is an issue directly related to this docker container, but it should be noted I now have no way to downgrade to the previous version as the dockerHub does not have previous version tags.

Any help would be greatly appreciated.

**Comment by dlandon** [comment]
I find this hard to believe since this docker is not Public.  Go to the Zoneminder forums for help with this issue.

**Comment by TheOneOgre** [comment]
I'm not sure what you mean it isn't public? The docker is listed publicly in the Community Applications for UNRAID no? I simply wanted a way to downgrade to the previous version just to get going until the zoneminder forums could pull something together.

**Comment by dlandon** [comment]
This docker is not available to the public.  This is the Unraid docker: [Unraid](https://github.com/dlandon/zoneminder.unraid)

You should really be posting these kinds of issues on the Unraid forum.

**Comment by TheOneOgre** [comment]
Weird. The UNRAID template links to dockerHub which links to this docker which is how I got here. I'm not sure if that was intentional but anyway, I'll try posting to the UNRAID forums then.
