### ISSUE TITLE
Invalid Configfile

### ISSUE THREAD

**Issue by querdenker2k** [dlandon/zoneminder.machine.learning#168]
I am using the latest image version.
When zmeventnotification tries to detect something i am getting:
`Mar  2 05:30:50 zoneminder /zm_detect.py[103393]: ERR [zmesdetect_m5] [Error running model: OpenCV(4.5.0) /root/opencv/modules/dnn/src/darknet/darknet_importer.cpp:207: error: (-212:Parsing error) Failed to parse NetParameter file: /var/lib/zmeventnotification/models/yolov4/yolov4.cfg in function 'readNetFromDarknet'`

I am just using the environment parameters:
```
- INSTALL_HOOK=1
- INSTALL_FACE=1
- INSTALL_TINY_YOLOV3=1
```
But in the configfile objectconfig.ini is yolov4 referenced.
What's the problem here?

Thanks

**Comment by dlandon** [comment]
You are referring to the previous ES docker that is no longer supported.
