### ISSUE TITLE
move mysql to separate container

### ISSUE THREAD

**Issue by tbowmo** [dlandon/zoneminder.machine.learning#170]
It shoulnd't be necessary to bake mysql server into the same container as zoneminder, and there are plenty of containers available for mysql / mariadb.

Would simplify things, and also allow for replicated instances of zoneminder on multiple machines, with a common database backend

**Comment by dlandon** [comment]
The container includes mysql for those that want an easy setup.  You can specify an external mysql database in the ZM configuration.

**Comment by alexyao2015** [comment]
For those interested in this, check out this https://github.com/zoneminder-containers/zoneminder-base
