### ISSUE TITLE
can not get new image from docker hub

### ISSUE THREAD

**Issue by ZhoraKornev** [dlandon/zoneminder.machine.learning#172]
I have error with last updates in docker-compose.yaml

ERROR: pull access denied for dlandon/zoneminder.machine.learning, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by DrBlokmeister** [comment]
Same issue here. Running docker on ubuntu 18.

**Comment by dlandon** [comment]
The docker is not available yet as it is still under development.
