### ISSUE TITLE
Default db credentials, missing from readme?

### ISSUE THREAD

**Issue by arthur798** [dlandon/zoneminder.machine.learning#173]
Hi I pulled the docker image and ran it similar to what is being said in readme file however I am getting issues that I can't connect to the database. I assumed that because nothing is provided in readme it's using default credentials, if not how do I set that up?

**Comment by dlandon** [comment]
The database is built into the docker.  You shouldn't need to do anything.  Are you trying to connect to an external database?

**Comment by ZhoraKornev** [comment]
Hi. Can you help me to connect to mysql DB inside docker.
I already forwarded port outside.
But receive message when trying to connect

8000][-1] Could not connect to address=(host=localhost)(port=43745)(type=master) : Could not connect to localhost:43745 : unexpected end of stream, read 0 bytes from 4 (socket was closed by server)
java.io.EOFException: unexpected end of stream, read 0 bytes from 4 (socket was closed by server).
