### ISSUE TITLE
SQLAlchemy 1.4.0 Breaks zm_detect.py

### ISSUE THREAD

**Issue by williamsrAndrew** [dlandon/zoneminder.machine.learning#174]
First, a note here is that I am still pulling the latest image from docker hub (dlandon/zoneminder) which looks to be deprecated, but I wanted to post this somewhere and I think this is the best place. 

I'm not exactly sure if this is an issue with zmeventnotification/pyzm or with this docker install, but sqlalchemy was updated to version 1.4.0 on Monday 3/15 and it causes zm_detect.py/pyzm to break when running object detection. 

```
root@zoneminder-574b887558-zfk2j:/# sudo -u www-data /var/lib/zmeventnotification/bin/zm_detect.py --config /etc/zm/objectconfig.ini --eventid 305 --monitorid 2 --debug
Unrecoverable error:__init__() got an unexpected keyword argument 'reflect' Traceback:Traceback (most recent call last):
  File "/var/lib/zmeventnotification/bin/zm_detect.py", line 531, in <module>
    main_handler()
  File "/var/lib/zmeventnotification/bin/zm_detect.py", line 223, in main_handler
    log.init(name='zmesdetect_' + 'm' + args.get('monitorid'), override=g.config['pyzm_overrides'])
  File "/usr/local/lib/python3.8/dist-packages/pyzm/ZMLog.py", line 166, in init
    meta = MetaData(engine,reflect=True)
TypeError: __init__() got an unexpected keyword argument 'reflect'
```

In order to fix this, I just need to downgrade sqlalchemy to 1.3.23. I'm not sure where this is specified in the install docker install, but either pyzm will need to be updated to use 1.4.0 or this docker should be set to install the proper version of sqlalchemy.

```
root@zoneminder-574b887558-zfk2j:/# pip3 install sqlalchemy==1.3.23
Collecting sqlalchemy==1.3.23
  Using cached SQLAlchemy-1.3.23-cp38-cp38-manylinux2010_x86_64.whl (1.3 MB)
Installing collected packages: sqlalchemy
  Attempting uninstall: sqlalchemy
    Found existing installation: SQLAlchemy 1.4.0
    Uninstalling SQLAlchemy-1.4.0:
      Successfully uninstalled SQLAlchemy-1.4.0
Successfully installed sqlalchemy-1.3.23
```

**Comment by Juggler00** [comment]
Thank you for finding that discrepancy! I was pulling my hair out trying to figure why my ES was no longer working.

**Comment by davolesh** [comment]
I'm only a week+ late but me too!! I was so confused....

It looks like [zmeventnotification ](https://github.com/pliablepixels/zmeventnotification/blob/master/CHANGELOG.md)was updated 5 days ago, but I had no idea how to update it because I am using "dlandon/zoneminder" in docker on unRaid.

I just went into the console in Zoneminder and ran your command and it worked! Thanks!

**Comment by dlandon** [comment]
The latest version of ES takes care of this issue.

**Comment by faspina** [comment]
Thanks all, should have checked here first. Spent 2 hours trying to figure out what happened after a docker restart. Will the dlandon/zoneminder:latest image be updated with the new ES to fix this.

**Comment by dlandon** [comment]
No.  That Docker is no longer supported.
