### ISSUE TITLE
High Shared Memory in ZM Docker container

### ISSUE THREAD

**Issue by Carmageddon** [dlandon/zoneminder.machine.learning#175]
Hi, My cameras are not loading in ZM, and possible culprit is this:
Load: 0.09 storage DB:6/151 Storage: Default: 21% /dev/shm: 100%

It seems shared memory setting is only configurable during image building, not runtime.

Is that something you could adjust? What is the current value?

**Comment by dlandon** [comment]
Read README.md on the github.
