### ISSUE TITLE
Probleme with pulling the machine.learning img

### ISSUE THREAD

**Issue by tremblay0934** [dlandon/zoneminder.machine.learning#181]
I do not know if this is related to 1.36 release, but the README.md command to start the container does not work and shows the attached error. 

For reference, my Docker hub account is logged in, so it seems that the dlandon/zoneminder.machine.learning:latest repo does not exist. Do you get the same behavior @dlandon  ?

Thanks for your awesome work, looking forward to donate when setup is deployed.

![err_docker](https://user-images.githubusercontent.com/53241667/120074992-78778880-c06d-11eb-858b-e710011f83de.png)

**Comment by dlandon** [comment]
The docker container is Private.  You cannot access it.

**Comment by Amunak** [comment]
Why? Why does the official ZoneMinder docs link to this repo, when it's not usable? What's the point of temporarily making it public, then private again?

**Comment by PiperMp3** [comment]
> 
> 
> Why? Why does the official ZoneMinder docs link to this repo, when it's not usable? What's the point of temporarily making it public, then private again?

I agree the docs should be updated if it's not made available.
However dlandon/zoneminder will still give a working image it seems.
