### ISSUE TITLE
Can't pull

### ISSUE THREAD

**Issue by threed-factory-store** [dlandon/zoneminder.machine.learning#183]
When I run the recommended "docker run" command, I get:

Unable to find image 'dlandon/zoneminder.machine.learning:latest' locally
docker: Error response from daemon: pull access denied for dlandon/zoneminder.machine.learning, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.

I get this even if I login to docker first using my github personal access token.

**Comment by dlandon** [comment]
The docker container is marked private while we run the GoFundMe campaign.  You can't access it.

**Comment by threed-factory-store** [comment]
Does this apply to zoneminder/zoneminder too?

And if I contribute, do I get access?

**Comment by dlandon** [comment]
> Does this apply to zoneminder/zoneminder too?

No.

And if I contribute, do I get access?

You don't necessarily have to contribute to get access.  I send emails to all contributors when I set the container Public.  You'd have to just watch the GoFundMe for that update.
