### ISSUE TITLE
Installed Zoneminder but can not locate config files.

### ISSUE THREAD

**Issue by SomebodySysop** [dlandon/zoneminder.machine.learning#187]
Running on Ubuntu 20 system.

Followed the install procedure here: https://github.com/dlandon/zoneminder.machine.learning

Zoneminder is up and running.

However, I cannot locate objectconfig.ini  files.  There is no /etc/zm folder.  I find zmeventnotification.ini in /mnt/Zonefinder

What file(s) do I modify if I need to change install configs?  I entered the wrong share size: --shm-size="8G"

**Comment by williamsrAndrew** [comment]
I don't really use the default docker run commands, but I believe you should just be able to re-run the docker run command with updated parameters to change things like --shm-size. I would highly recommend using something like docker-compose to keep track of your configs and easily make changes without having to redo the entire docker run command. If you wanted to get even fancier, you could use something like Portainer to manage your containers from a web interface. 

As far as the Zoneminder specific config files, they will be located in the volume that you specified in the run command. It looks like you just used the default so inside of "/mnt/Zoneminder" you will have all of your config files. "objectconfig.ini" will be in "/mnt/Zoneminder/hook"

**Comment by SomebodySysop** [comment]
Thank you very much.  The config files are in /mnt/Zoneminder directory tree.  And, I was able to re-run docker command with correct share size.
